In [1]:
import numpy as np

# arrary 的创建和操作
 可以使用np.arrary 将list转换为ndarry

In [2]:
alist = [1, 2, 3]
arr = np.array(alist)

 也可以使用zeros和arange （0到100）初始化

In [3]:
arr1 = np.zeros(5)
arr2 = np.arange(100)
arr3 = np.arange(10,100)
arr4 = np.linspace(0, 1, 100)
print(arr1, arr2, arr3, arr4)


[0. 0. 0. 0. 0.] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99] [0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535


 一样可以使用创建二维，或者使用上述方法

In [4]:
image = np.zeros((5,5))
cube = np.zeros((5,5,5)).astype(int) + 1
arr2d = arr2.reshape(10,10)
arr3d = np.reshape(arr2, (1, 10, 10))
print(image.shape, cube.shape, arr2d.shape, arr3d.shape)

(5, 5) (5, 5, 5) (10, 10) (1, 10, 10)


# 数据类型
 在arrary 的data type 也可以通过相应的参数进行设置

In [5]:
arr = np.zeros(2, dtype=int)


# array 索引
## 分片索引
  array 的操作和分片操作和python的List操作一样，但表达上更为方便。

In [6]:
alist=[[1,5],[3,4]]
alist[0][1]

arr = np.array(alist)
arr[0,1]
arr[1,:]

array([3, 4])

## 用多维array去索引数组 相关知识总结在OneNote上。

In [7]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

[1 4 5]
[1 4 5]


## 布尔式索引
 可以使用 ```
  x[y>2]```这样来引用数组，y>2 返回的是一个布尔变量数组
 x[y>2] 只会引用布尔变量为true的数组元素。

In [8]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2) 
print(a[bool_idx])
print(a[a > 2])   


[3 4 5 6]
[3 4 5 6]


# 数组的增改删查
## 增
 在创建一项已经说明了。append(),
## 改
### 数学运算
 数学运算中(+-*/)，照理array是应该统一维度的。但是numpy中有broadcasting的机制，可以减少赋值的循环，使循环在C语言中实现而不是在python中实现，减少了运行时间。

In [9]:
x = np.array([1, 2])
y = np.array([[3], [4]])
b = 2
print(x+y)
print(b*x)

[[4 5]
 [5 6]]
[2 4]


1. 如果两个数组在维度中大小相同，
2. 或者其中一个数组在该维度中大小为1，那么这两个数组在维度中是兼容的。
3. 如果数组在所有维度上都兼容，则可以将它们一起广播。进入翻译页面
## 查
  np.where函数可以使用返回满足对应条件的索引，def where(condition, x, y)符合条件输出x，不符合输出y。在一维的情况下，xy缺省，即返回条件式为true的索引。 二维情况，返回的是坐标，竖着看即是坐标。

In [10]:
arr = np.arange(4,10)
arr2 = arr.reshape(2,3)
index = np.where(arr > 5)
print(index)
index = np.where(arr2 > 5)
print(index)


(array([2, 3, 4, 5], dtype=int64),)
(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


 对于麻烦的a[np.where(a>5)] 提取大于5 的元素来说，直接使用arr[arr>5] 这形式就容易多了.无论维数，都是等价的。
## 删
 删除操作可以使用np.delete 来进行操作

In [11]:
np.delete

<function numpy.lib.function_base.delete(arr, obj, axis=None)>